### ISSUE TITLE
"fx infra"

### ISSUE THREAD

**Issue by metrue** [metrue/fx#366]
## Setup
* Docker
```
fx infra setup --name <name> -type docker --host <user@host>
```
* K8S

```
fx infra setup <name> -type k8s --master <user@host> --agents <user1@host1, user2@host2....>
```

## List

```
fx infra list

- name1   *
  status: 
  ip: 
- name2
  status:
  cluster: 
     master: 
     agent:
....
```

## Use

set infra to be active.
```
fx infra use <name>
```

**Comment by metrue** [comment]
```yml
infras:
  docker-1:
    type: docker
    host: 1.1.1.1
    user: root
  docker-2:
    host: 2.2.2.2
    user: root
  k8s-1:
    type: k8s
    config: k8s-1.kubeconfig
  k8s-2:
    type: k8s
    config: k8s-2.kubeconfig
context: docker-1
```
